### ISSUE TITLE
Login Page 

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#109]
We need a Login Page so users are able to get their preferred focus on the map.

**Comment by snowcov** [comment]
Set up OAuth for google authentication.
Attempted to implement google authentication - Had issues likely arising from not having a proper domain.
Pivoting to implement custom login form for the time being.

![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/c3dae311-5f7f-4956-9f81-a8ebeb60aea0)


![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/d3954c6d-ecf3-447e-ad94-d6e9f4880216)

**Comment by snowcov** [comment]
Reference:
https://developers.google.com/identity/sign-in/web/sign-in

**Comment by snowcov** [comment]
Created Working Registration page based on CSS from:
https://codeshack.io/secure-registration-system-php-mysql/

Link (after running flask): http://127.0.0.1:5000/register

Hashes password on input for security.
Used Flask implementation to communicate with database and check if username or email from form submission were already in the database, if found, user is redirected to the registration page and nothing is added to database.
If successful and username and email are unique, then data will be added to the database and user is redirected to the mapping webpage.

Next Steps:
Adding Session Variables
Adding Login
Adding Settings Page/Options to Registration to Customize user experience

**Comment by snowcov** [comment]
Reworked hashing for registration and how the registration and login pages interacted.

Reference for code and styling: https://codeshack.io/login-system-python-flask-mysql/



![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/36649d13-db55-4779-8fbb-cb357aa91d75)



![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/44befbb9-996b-4883-954a-9516ec978c10)



![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/b4eb2ee5-19a0-453b-82d7-b2bda6bbfe25)

Next Steps:
Adding Session Variables
Adding Settings Page/Options to Registration to Customize user experience

**Comment by snowcov** [comment]
Update: Temporarily Complete

Session Variables set up, with working registration and login. There is not much too do given the lack of information on this part, I will keep the ticket open, but it will not a primary concern at the moment.

Future Points: 
- Comprehensive Registration requiring further input from user
- Improved functionality and customization in settings page 
- New Styling for login/register/profile
- Refactoring to create a new python file for the login/register links
