### ISSUE TITLE
Allow the DataPoints to be Groupable

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#14]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/d988d695-456d-4816-a751-858090dc1317)

**Comment by Pham-Vincent** [comment]
These will Probably need to be grouped in Quadrants somehow?

**Comment by Pham-Vincent** [comment]
https://developers.google.com/maps/documentation/javascript/marker-clustering
 This seems like the best/Most Optimal Way of Working with the Map Clustering

**Comment by snowcov** [comment]
Added Clustering
