### ISSUE TITLE
Update Profile Page and Preference 

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#155]
Pg 8
![image](https://github.com/user-attachments/assets/a919854f-820c-489b-be7e-ac419994b498)
![image](https://github.com/user-attachments/assets/0c30d5fc-0d38-4684-a6c4-8ae1773aceb9)

**Comment by snowcov** [comment]
Task Completed:

- No functionality currently, all styling applied to mirror Kanika's Design.
