### ISSUE TITLE
State Highlighting

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#156]
Pt 12
![image](https://github.com/user-attachments/assets/cc30dca8-7ccc-4d67-addd-2c95a005489b)

**Comment by snowcov** [comment]
Task Completed:

- Used Administrative zone to highlight states. This is a built in feature to google maps API to highlight specific layers around the world.

![image](https://github.com/user-attachments/assets/ba21a1bd-cab9-43c2-91de-18dc9bb18d52)
