### ISSUE TITLE
Overlapping Markers -> Spidering

### ISSUE THREAD

**Issue by snowcov** [Pham-Vincent/Equitable-Water-Solutions#18]
![Capture](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/e6f058ed-0f3a-47dc-b811-2e1a497833cd)

Figure out what to do with overlapping coordinate markers.

**Comment by Pham-Vincent** [comment]
Maybe this will work? 
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/708f6d56-e8ad-4b69-b832-da700c1dc74b)

**Comment by Pham-Vincent** [comment]
https://developers.google.com/maps/documentation/javascript/examples/marker-collision-management

**Comment by snowcov** [comment]
Closing Issue --- Fixed with the addition of random offsets.
