### ISSUE TITLE
{new feature} Map boundary line

### ISSUE THREAD

**Issue by Will-lamuth** [Pham-Vincent/Equitable-Water-Solutions#19]
https://developers.google.com/maps/documentation/javascript/examples/boundaries-simple
i think this would be useful to show state boundaries between the DMV. could be used in legend.

**Comment by snowcov** [comment]
![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/c6e670b6-bbc5-47e4-9c36-91fec13cb8d3)

Created Chesapeake Bay outline, have full knowledge and capability of how to outline states as well.
