### ISSUE TITLE
Issue with ForEach 

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#28]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/97b53585-bd57-4e6a-a7bb-35c1197162a8)
Seems like there is an Issue with the ForEach Function, Might have been when I merged would you take a look?

**Comment by snowcov** [comment]
I believe this is just caused by certain items in the json file being left blank. It seems to be printing data points normally otherwise, I do not think it is any major problem. Will keep eye out in future.
