### ISSUE TITLE
Trim Down Data 

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#35]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/f6770b28-0a07-467c-a070-6dffcab960b1)

Figure out what to do with some data some of it is N/A or Unusable and some of them have classified names  and some have bad coordinates

**Comment by snowcov** [comment]
Disabled points with (0, 0) in PHP. This problem only occurs in old data sets, new MD data set does not have this issue.
