### ISSUE TITLE
Update Map Clustering Feature (Look into Before July)

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#42]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/466f573d-6a13-418e-b8e7-cbfa03306b9f)

This Map Cluster Feature Will be gone on 8/01/2024

**Comment by snowcov** [comment]
Updated to newer Clustering that works for advanced markers
