### ISSUE TITLE
Marker Coloring

### ISSUE THREAD

**Issue by snowcov** [Pham-Vincent/Equitable-Water-Solutions#43]
Need to add unique color to distinguish between marker type.
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/d79f5acd-cb46-457c-a917-55baba5f015e)

**Comment by Will-lamuth** [comment]
Advanced markers allow for coloring

**Comment by Pham-Vincent** [comment]
Currently You only changed 1 data marker to one color, You should try to implement multiple different markers at the same time.
https://developers.google.com/maps/documentation/javascript/advanced-markers/basic-customization
