### ISSUE TITLE
Fix Ya Comments >:(

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#46]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/7e572793-3aae-45da-a4c1-15cc2e2104ac)
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/c478ef9b-15aa-406a-bf26-ecd333fdc5ea)

**Comment by Will-lamuth** [comment]
made them beefier
