### ISSUE TITLE
random clustering

### ISSUE THREAD

**Issue by Will-lamuth** [Pham-Vincent/Equitable-Water-Solutions#49]
<img width="530" alt="Screen Shot 2024-04-07 at 10 11 44 PM" src="https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252007/bfc4d62b-ad64-41df-928c-6ade812b884a">

**Comment by snowcov** [comment]
![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/ea896747-dc9f-4341-9ad1-f20d8c96c0c1)

Found several coordinates with Latitude (range -90 to 90) that were 99. This is out of scope and causes the clustering.

**Comment by snowcov** [comment]
![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/92055433-b075-45a0-9750-f3d2fb75725e)

Deleted all points from database with Latitude > 90, then ran the php script to create a new JSON. The 26 points are gone.
