### ISSUE TITLE
Loading Screen?

### ISSUE THREAD

**Issue by snowcov** [Pham-Vincent/Equitable-Water-Solutions#50]

**Comment by snowcov** [comment]
The webpage loads datapoints and graphs quite slowly. Perhaps consider adding a loading screen.


![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/120518302/cabf6046-1e50-4302-880d-c5a7b4f5b20e)

**Comment by Pham-Vincent** [comment]
Implemented a loading screen to differentiate if a graph has a loading 

![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/a89a6553-d004-43e4-b4f0-4e776dbf0ad2)
