### ISSUE TITLE
Overlay 

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#6]
There is an Overlay Problem With Your Code 
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/8d9129d8-5eca-4ef4-bd52-495cea0046b0)

**Comment by Will-lamuth** [comment]
completed
when marker popup is open its hover title will not appear but others will

**Comment by Pham-Vincent** [comment]
![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/bc29a0aa-2fa3-4527-87f8-4b8cb0eb86e9)

This is still an issue I don't know if u look into it it this is pretty low priority.

If I click on a marker then hover on another closer one to it and then try to click on the see more option its block

**Comment by Will-lamuth** [comment]
was fixed after changing to advanced markers
