### ISSUE TITLE
Can You Add an extra Condition for disabling first level popup

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#67]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/ff614d84-d66e-4eb7-8b72-008fd73df7c1)
Sometimes it glitches and stayss on the screen even when not hovering, Probably an issue to do with clustering would you add an extra condition if clicking anywhere else on the map it will disappear

**Comment by Will-lamuth** [comment]
added additional map actionlistener to close upon clicking
