### ISSUE TITLE
Disable clustering when hiding markers

### ISSUE THREAD

**Issue by Will-lamuth** [Pham-Vincent/Equitable-Water-Solutions#69]
You can hide the markers using the legend but the clustering prevents all markers from being hidden. Need to figure out how to temporarily disable clustering.

**Comment by Pham-Vincent** [comment]
https://stackoverflow.com/questions/39300264/update-clustered-markers-in-google-map-with-map-filters

**Comment by snowcov** [comment]
Resolved - Improved legend functionality to Add/Remove Markers from Clustering.
