### ISSUE TITLE
Refactor Your Ajax Code

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#72]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/2db2f134-8ef4-45e7-b1a6-77575b66990f)
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/f5a0e889-959e-4288-ae40-3f4afe6686c1)

Multiple similar code called multiple times Can definitely be refactored

**Comment by snowcov** [comment]
REFACTORED
