### ISSUE TITLE
Create Custom Images for markers

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#80]
Need custom images for markers like 

![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/73cf25fe-f19b-45b6-b068-46b1bfbb395c)

**Comment by Will-lamuth** [comment]
-VA markers stay default upon advisor request
-MD markers follow unique icon+marker design
