### ISSUE TITLE
Create Too Many Marker Cluster Objects 

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#81]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/97bb0a2c-cc38-488e-a780-a31efd2cf72a)
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/4b0f91c7-87bb-4761-a51a-73827433acab)

**Comment by snowcov** [comment]
Fixed this; since we imported MarkerClusterer in HTML, we need to use "new markerClusterer.MarkerClusterer" to create the clustering object, and can't just use "new MarkerClusterer" Renamed this object for clarity.
