### ISSUE TITLE
Add a Checkall Feature

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#84]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/794e1e70-7d76-4717-b0a7-bce7c2beea34)
Add a feature to select and deselect all 

Also add a feature to select all in specific Water Withdrawls

**Comment by Will-lamuth** [comment]
i added just one select all checbox

**Comment by Pham-Vincent** [comment]
I Would Like you to Instead have a Select All Checkbox for that specific Category For Example right next to the Water Withdrawl (But you Can keep the select all at the Bottom Still) 



![Image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/26ae517e-5684-461b-824b-d799cd9eb3e9)

**Comment by Will-lamuth** [comment]
I added a checkall feature for water withdrawal to in legendFunction.js
