### ISSUE TITLE
Marker Cluster Bugged

### ISSUE THREAD

**Issue by Pham-Vincent** [Pham-Vincent/Equitable-Water-Solutions#90]
![image](https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252560/3bb18c0d-447e-4d28-8a59-e381e50d0914)

I Zoomed in Max but the Cluster didn't disappear

**Comment by snowcov** [comment]
Changed Minimum Cluster Size to 3, This should fix it.
