### ISSUE TITLE
Use consistent font

### ISSUE THREAD

**Issue by Will-lamuth** [Pham-Vincent/Equitable-Water-Solutions#96]
<img width="637" alt="Screen Shot 2024-04-30 at 1 35 37 PM" src="https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252007/3c380cf1-0b0c-4c6d-a123-edc7824aa2e2">

why two different fonts

**Comment by Pham-Vincent** [comment]
Fixed the Font to look consistent in the App.py File
