### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Will-lamuth** [Pham-Vincent/Equitable-Water-Solutions#97]
<img width="1438" alt="Screen Shot 2024-04-30 at 1 39 03 PM" src="https://github.com/Pham-Vincent/Equitable-Water-Solutions/assets/156252007/0f2a5b1a-ab50-435b-8178-c6b54410c021">

when you click open marker popup this error appears in the console

**Comment by snowcov** [comment]
It was attempting to call Clustering Function several times whenever any ajax completed. Adjusted the code to only created clusters once. Additionally, renamed clustering variable for better clarity.
